name: youtube_player
description: A flutter plugin to play Youtube Videos "inline" without API Key in range of Quality(240p ,360p ,480p ,720p and 1080p).
version: 0.5.0
author: Sarbagya Dhaubanjar <mail@sarbagyastha.com.np>
homepage: https://github.com/sarbagyastha/youtube_player

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  open_iconic_flutter: ^0.3.0
  meta: ^1.1.6
  flutter_android_pip: ^0.0.2
  screen: ^0.0.4


flutter:

  plugin:
    androidPackage: np.com.sarbagyastha.youtubeplayer
    pluginClass: YoutubePlayerPlugin

